steps:
  - label: "丘뙖잺 Configure environment"
    command: .buildkite/common.sh
    key: config
  - label: "iOS: Bazel 游릭 Cache"
    command: .buildkite/ios_cache.sh
    key: build_ios_cache
    depends_on: "config"
  - label: "iOS: Bazel 游리 No cache"
    command: .buildkite/ios_nocache.sh
    key: build_ios_nocache
    depends_on: "config"
  - label: "Android: Gradle 游릭 Cache"
    command: .buildkite/android_cache.sh
    key: build_android_cache
    depends_on: "config"
  - label: "Android: Gradle 游리 No cache"
    command: .buildkite/android_nocache.sh
    key: build_android_nocache
    depends_on: "config"
    