steps:
  - label: "丘뙖잺 Configure environment"
    command: .buildkite/common.sh
    key: config
  - label: "iOS: Bazel 游릭 Cache"
    command: .buildkite/ios_bazel_cache.sh
    key: build_ios_bazel_cache
    depends_on: "config"
  - label: "iOS: Bazel 游리 No cache"
    command: .buildkite/ios_bazel_nocache.sh
    key: build_ios_bazel_nocache
    depends_on: "config"
  - label: "Android: Gradle 游릭 Cache"
    command: .buildkite/android_gradle_cache.sh
    key: build_android_gradle_cache
    depends_on:
      - step: "config"
      - step: "build_ios_bazel_cache" # not really a dep, but run 'cache-enabled' steps one after another sequentially
  - label: "Android: Gradle 游리 No cache"
    command: .buildkite/android_gradle_nocache.sh
    key: build_android_gradle_nocache
    depends_on: "config"
  - label: "iOS: Tuist 游리 No cache"
    command: .buildkite/ios_tuist_nocache.sh
    key: build_ios_tuist_nocache
    depends_on: "config"
  - label: "iOS: Tuist 游릭 Cache"
    command: .buildkite/ios_tuist_cache.sh
    key: build_ios_tuist_cache
    depends_on:
      - step: "config"
      - step: "build_android_gradle_cache" # not really a dep, but run 'cache-enabled' steps one after another sequentially